{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# ⚡ 🇹🇭 เตรียมชุดข้อมูลเสียงภาษาไทย (MCV v24) [Speedrun Edition]\n",
        "\n",
        "ฉบับสปีดรัน: เร็วที่สุดเท่าที่ระบบ Kaggle จะทำได้! \n",
        "เราจะใช้เทคนิค **Advanced Data Engineering 3 ประสาน**: \n",
        "1. `Aria2 Multi-connection`: โหลดไฟล์ผ่าน 16 ท่อ ลดเวลาดาวน์โหลดไฟล์ 8GB จาก 15 นาทีเหลือ ไม่เกิน 3 นาที\n",
        "2. `On-the-fly Tar-Streaming`: แตกไฟล์บนอากาศ (RAM) ไม่เขียนไฟล์ .mp3 ลงดิสก์เลยแม้แต่ไบต์เดียว ลดเวลาแตกไฟล์ทิ้งไป 100%\n",
        "3. `FFmpeg Stdin Pipe`: ปั๊มไบต์เสียงลงคอ FFMPEG โดยตรง ประหยัด I/O ขั้นสุด!\n",
        "---\n",
        "*🎯 เป้าหมาย:* โฟลเดอร์ `dataset/` จะเต็มไปด้วยไฟล์ `.wav` ความถี่ 24000Hz สำหรับ InworldTTS ภายใน 10 นาที!"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ติดตั้งอาวุธหนัก: aria2 สำหรับโหลดไฟล์ความเร็วสูงสุดทะลุกำแพง (16 threads)\n",
        "!apt-get update -qq && apt-get install -y -qq aria2\n",
        "!pip install pandas requests psutil tqdm -q"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### ⚙️ ส่วนที่ 1: ตั้งค่าระบบ & RAM Disk (Configuration)\n",
        "เราจะใช้ระบบ `/dev/shm` (RAM Disk) เป็นจุดพักไฟล์ เพื่อให้การประมวลผลอ่านเขียนเร็วขึ้นก้าวกระโดด"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "import os\n",
        "import subprocess\n",
        "import sys\n",
        "import tarfile\n",
        "import concurrent.futures\n",
        "import multiprocessing\n",
        "import psutil\n",
        "import pandas as pd\n",
        "import requests\n",
        "from tqdm import tqdm\n",
        "\n",
        "MDC_API_KEY = \"6799035d029e9bcf52cea5e84637baf19f377d387d3ab1f3ef4f4cc0235f5ccf\"\n",
        "MDC_DATASET_ID = \"cmj8u3pvx00r9nxxb1yo5z53z\"\n",
        "MDC_API_BASE = \"https://datacollective.mozillafoundation.org/api\"\n",
        "\n",
        "# ใช้อากาศ (RAM) เป็นทางผ่าน! ชี้โฟลเดอร์ทำงานย่อยไปที่ /dev/shm (Shared Memory ของ Linux)\n",
        "RAM_DIR = \"/dev/shm/mcv_thai_ram\"\n",
        "os.makedirs(RAM_DIR, exist_ok=True)\n",
        "\n",
        "KAGGLE_WORKING = \"/kaggle/working\"\n",
        "DOWNLOAD_DIR = os.path.join(KAGGLE_WORKING, \"mcv_thai_raw\")\n",
        "OUTPUT_WAV_DIR = os.path.join(KAGGLE_WORKING, \"dataset\", \"th_wavs\")    # ผลลัพธ์ .wav เก็บลงดิสก์ Kaggle สบายๆ\n",
        "OUTPUT_JSONL = os.path.join(KAGGLE_WORKING, \"dataset\", \"train.jsonl\")\n",
        "\n",
        "TARGET_SAMPLE_RATE = 24000\n",
        "TARGET_CHANNELS = 1\n",
        "\n",
        "# จำนวนสูงสุดที่ต้องการเทรน \n",
        "MAX_CLIPS = 10000"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 📥 ส่วนที่ 2: ดาวน์โหลดระดับเครื่องจักรด้วย Aria2\n",
        "ดึงไฟล์ลงมาในเสี้ยววิ ด้วยการแตกสายดาวน์โหลด 16 เส้นขนานกัน"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"=\" * 60)\n",
        "print(\"Step 1: Hitting Mozilla API & Downloading with Aria2 (16x Speed)\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "os.makedirs(DOWNLOAD_DIR, exist_ok=True)\n",
        "\n",
        "response = requests.post(\n",
        "    f\"{MDC_API_BASE}/datasets/{MDC_DATASET_ID}/download\",\n",
        "    headers={\"Authorization\": f\"Bearer {MDC_API_KEY}\", \"Content-Type\": \"application/json\"},\n",
        ")\n",
        "download_url = response.json().get(\"downloadUrl\") or response.json().get(\"url\")\n",
        "\n",
        "tar_path = os.path.join(DOWNLOAD_DIR, \"cv_thai_v24.tar.gz\")\n",
        "\n",
        "if os.path.exists(tar_path):\n",
        "    print(f\"File already exists: {tar_path}, skipping download.\")\n",
        "else:\n",
        "    print(f\"Executing Aria2 Multi-Connection Download (16 Threads)...\")\n",
        "    # โหลดไฟล์ 8GB ด้วยความเร็วสูงสุดຂອງเซิร์ฟเวอร์ Kaggle!\n",
        "    subprocess.run([\n",
        "        \"aria2c\", \"-x\", \"16\", \"-s\", \"16\", \"-k\", \"1M\",\n",
        "        \"-o\", \"cv_thai_v24.tar.gz\", \"-d\", DOWNLOAD_DIR, download_url\n",
        "    ], check=True)\n",
        "    print(f\"\\n🚀 Download Complete!\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🔍 ส่วนที่ 3: ดูดข้อมูล TSV จาก .tar.gz ตรงๆ เข้า RAM (ไม่แตกไฟล์ใหญ่)\n",
        "แทนที่จะแตกไฟล์ 8GB เป็นชั่วโมง เราจะเอามือล้วงเข้าไปหยิบเฉพาะตารางสารบัญ `.tsv` ออกมาใส่ RAM เลย!"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"Step 2: Stealth TSV Extraction into RAM\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "validated_tsv_path = os.path.join(RAM_DIR, \"validated.tsv\")\n",
        "clip_durations_path = os.path.join(RAM_DIR, \"clip_durations.tsv\")\n",
        "\n",
        "if not os.path.exists(validated_tsv_path):\n",
        "    print(\"Opening .tar.gz and extracting ONLY essential TSV files into RAM...\")\n",
        "    found_val = False\n",
        "    with tarfile.open(tar_path, \"r:gz\") as tar:\n",
        "        for member in tar.getmembers():\n",
        "            if member.name.endswith(\"validated.tsv\"):\n",
        "                with open(validated_tsv_path, \"wb\") as f_out:\n",
        "                    f_out.write(tar.extractfile(member).read())\n",
        "                found_val = True\n",
        "            elif member.name.endswith(\"clip_durations.tsv\"):\n",
        "                with open(clip_durations_path, \"wb\") as f_out:\n",
        "                    f_out.write(tar.extractfile(member).read())\n",
        "            \n",
        "            if found_val and os.path.exists(clip_durations_path):\n",
        "                break # ได้ไฟล์ที่ต้องการครบแล้ว หยุดค้นหาทันที ประหยัดเวลา!\n",
        "else:\n",
        "    print(\"TSVs already exist in RAM.\")\n",
        "\n",
        "# อ่านตารางข้อมูลในพริบตา\n",
        "df = pd.read_csv(validated_tsv_path, sep=\"\\t\")\n",
        "if MAX_CLIPS and MAX_CLIPS < len(df):\n",
        "    df = df.head(MAX_CLIPS)\n",
        "\n",
        "print(f\"Aiming to process {len(df)} validated clips.\")\n",
        "\n",
        "durations_dict = {}\n",
        "if os.path.exists(clip_durations_path):\n",
        "    df_durations = pd.read_csv(clip_durations_path, sep=\"\\t\")\n",
        "    for _, r in df_durations.iterrows():\n",
        "        durations_dict[r[\"clip\"]] = float(r[\"duration[ms]\"]) / 1000.0"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### ⚡ ส่วนที่ 4: เผา RAM! สตรีมมิ่งไฟล์เสียงเข้าท่อ Piped-FFMPEG\n",
        "อ่านไฟล์ .tar.gz แบบเส้นตรง (Sequential) เจอก้อนข้อมูล MP3 ที่เราต้องการเมื่อไหร่ ดันเข้าคิวให้ FFmpeg กลืนแปลงเป็น WAV สดๆ เลย (ไม่มีไฟล์ mp3 จริงๆ โผล่มาบนฮาร์ดดิสก์ให้กวนใจ)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "from multiprocessing import Manager\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"Step 3: On-The-Fly Tar Streaming to FFmpeg \\n(No MP3s will be written to disk!)\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "os.makedirs(OUTPUT_WAV_DIR, exist_ok=True)\n",
        "\n",
        "# เตรียมรายชื่อไฟล์ที่ต้องการดึง (จะได้ไม่ต้องประมวลผลไฟล์ขยะ)\n",
        "wanted_filenames = set(df[\"path\"].dropna().tolist())\n",
        "row_dict = df.set_index(\"path\").to_dict(\"index\")\n",
        "\n",
        "successful = 0\n",
        "failed = 0\n",
        "jsonl_lines = []\n",
        "\n",
        "# ฟังก์ชันแปลงเสียงแบบ Piped_Stdin (รับ Bytes ดิบๆ ไม่ใช่ไฟล์!)\n",
        "def process_audio_bytes(mp3_bytes, mp3_filename):\n",
        "    wav_filename = mp3_filename.replace(\".mp3\", \".wav\")\n",
        "    wav_path = os.path.join(OUTPUT_WAV_DIR, wav_filename)\n",
        "    \n",
        "    # ป้อนไบต์เข้าทางท่อ (pipe:0) และให้ออกมาเป็นไฟล์ที่เซฟลงท่อทำงาน\n",
        "    process = subprocess.Popen(\n",
        "        [\n",
        "            \"ffmpeg\", \"-y\", \"-i\", \"pipe:0\", \n",
        "            \"-ar\", str(TARGET_SAMPLE_RATE),\n",
        "            \"-ac\", str(TARGET_CHANNELS),\n",
        "            \"-threads\", \"1\",  # สำคัญ: ห้าม FFmpeg แย่ง CPU\n",
        "            wav_path\n",
        "        ],\n",
        "        stdin=subprocess.PIPE,  \n",
        "        stdout=subprocess.DEVNULL,\n",
        "        stderr=subprocess.DEVNULL\n",
        "    )\n",
        "    process.communicate(input=mp3_bytes)\n",
        "    \n",
        "    if process.returncode == 0:\n",
        "        # เช็คเวลาจากตาราง ไม่ต้องพึ่ง ffprobe ค้นหาให้เมื่อย\n",
        "        duration = durations_dict.get(mp3_filename, 5.0) \n",
        "        if duration > 30.0:\n",
        "            if os.path.exists(wav_path): os.remove(wav_path)\n",
        "            return \"failed\", None\n",
        "            \n",
        "        row = row_dict[mp3_filename]\n",
        "        result_json = json.dumps({\n",
        "            \"transcript\": str(row[\"sentence\"]),\n",
        "            \"language\": \"th\",\n",
        "            \"wav_path\": wav_path,\n",
        "            \"duration\": round(duration, 2),\n",
        "            \"sample_rate\": TARGET_SAMPLE_RATE\n",
        "        }, ensure_ascii=False)\n",
        "        return \"ok\", result_json\n",
        "    return \"failed\", None\n",
        "\n",
        "\n",
        "# เริ่มเปิดการอ่าน .tar.gz แบบสตรีมไหลต่อเนื่อง (Sequential Streaming)\n",
        "\n",
        "# เปลี่ยนจาก ThreadPool เป็น ProcessPool เพื่อให้ทะลวง CPU ได้สมบูรณ์ 100% (Bypass GIL!)\n",
        "num_workers = min(multiprocessing.cpu_count() * 2, 32)\n",
        "print(f\"Scanning Master Archive and extracting files sequentially... ({num_workers} Parallel Processes)\")\n",
        "\n",
        "mp3_data_list = []\n",
        "with tarfile.open(tar_path, \"r|gz\") as tar:\n",
        "    for member in tar:\n",
        "        filename = os.path.basename(member.name)\n",
        "        if filename in wanted_filenames:\n",
        "            mp3_bytes = tar.extractfile(member).read()\n",
        "            mp3_data_list.append((mp3_bytes, filename))\n",
        "            wanted_filenames.remove(filename)\n",
        "            if not wanted_filenames:\n",
        "                break\n",
        "\n",
        "print(f\"Found all {len(mp3_data_list)} items. Launching aggressive chunked formatting...\")\n",
        "\n",
        "# กระจายงานแบบ Multi-processing (คอร์แท้)\n",
        "executor = concurrent.futures.ProcessPoolExecutor(max_workers=num_workers)\n",
        "futures = []\n",
        "pbar = tqdm(total=len(mp3_data_list), desc=\"Converting in Real-Time\")\n",
        "\n",
        "for item in mp3_data_list:\n",
        "    future = executor.submit(process_audio_bytes, item[0], item[1])\n",
        "    future.add_done_callback(lambda p: pbar.update(1))\n",
        "    futures.append(future)\n",
        "\n",
        "for future in concurrent.futures.as_completed(futures):\n",
        "    status, line = future.result()\n",
        "    if status == \"ok\":\n",
        "        successful += 1\n",
        "        jsonl_lines.append(line)\n",
        "    else:\n",
        "        failed += 1\n",
        "\n",
        "pbar.refresh()\n",
        "pbar.close()\n",
        "executor.shutdown()\n",
        "\n",
        "print(f\"\\nParallel Processing Conversion complete!\")\n",
        "print(f\"  Successful: {successful}\")\n",
        "print(f\"  Failed: {failed}\")\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🧹 ส่วนที่ 5: เขียนตาราง Train & ทำลายหลักฐานให้สิ้นซาก\n",
        "ลบไฟล์ .tar.gz 8GB และ RAM disk ทิ้งหมด เพื่อให้คุณกด Save Version เอาเฉพาะ Folder ข้อมูลสกัดบริสุทธิ์ออกมา\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"Step 4: Wrap up & Aggressive Cleanup\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "os.makedirs(os.path.dirname(OUTPUT_JSONL), exist_ok=True)\n",
        "import sys\n",
        "with open(OUTPUT_JSONL, \"w\", encoding=\"utf-8\") as f:\n",
        "    f.write(\"\\n\".join(jsonl_lines))\n",
        "    f.flush()\n",
        "    os.fsync(f.fileno())\n",
        "\n",
        "print(f\"Written {len(jsonl_lines)} entries to: {OUTPUT_JSONL}\")\n",
        "\n",
        "for temp_path in [DOWNLOAD_DIR, RAM_DIR]:\n",
        "    if os.path.exists(temp_path):\n",
        "        print(f\"Removing temporary master directory: {temp_path}...\")\n",
        "        # shutil.rmtree() sometimes struggles with RAM disk in Kaggle, so using forced system call\n",
        "        os.system(f\"rm -rf {temp_path}\")\n",
        "        \n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"✅ SPEEDRUN COMPLETE! Dataset is exclusively ready for InworldTTS.\")\n",
        "print(\"=\" * 60)\n",
        "print(f\"  WAV Dir:  {OUTPUT_WAV_DIR}\")\n",
        "print(f\"  JSONL:    {OUTPUT_JSONL}\")\n",
        "print(f\"  Clips:    {len(jsonl_lines)}\")\n",
        "print(f\"  Bitrate:  {TARGET_SAMPLE_RATE}Hz Mono\")",
        "\nsys.stdout.flush()\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🔊 ส่วนที่ 6: ดาวน์โหลด xcodec2 Audio Codec (หูและปากของโมเดล)\n",
        "xcodec2 คือโปรแกรมแปลงเสียง ↔ รหัสตัวเลข ที่ Llama จะใช้ในการ:\n",
        "1. **Encoder (หู):** แปลงไฟล์เสียง .wav → Acoustic Tokens สำหรับเทรน\n",
        "2. **Decoder (ปาก):** แปลง Acoustic Tokens → ไฟล์เสียง .wav สำหรับ Inference\n",
        "\n",
        "> 💡 ดาวน์โหลดไว้ใน Output ของ Notebook 1 นี้ เพื่อให้ Notebook 2 ใช้เป็น Input ฟรีๆ\n",
        "> ไม่ต้องเสียเวลาโหลดซ้ำทุกรอบ และไม่กิน Disk ฝั่ง Working ตอนเทรน!"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ดาวน์โหลด xcodec2 checkpoint (~1.1GB) จาก HuggingFace\n",
        "# ไฟล์นี้จะถูกรวมอยู่ใน Output Dataset ของ Notebook 1\n",
        "# เมื่อ Notebook 2 เพิ่ม Output นี้เป็น Input → จะอ่านไฟล์ได้ฟรีๆ ไม่กิน Working Disk\n",
        "\n",
        "XCODEC2_DIR = os.path.join(KAGGLE_WORKING, 'xcodec2_ckpt')\n",
        "XCODEC2_PATH = os.path.join(XCODEC2_DIR, 'checkpoint.pt')\n",
        "XCODEC2_URL = 'https://huggingface.co/HKUSTAudio/xcodec2/resolve/main/ckpt/epoch%3D4-step%3D1400000.ckpt'\n",
        "\n",
        "os.makedirs(XCODEC2_DIR, exist_ok=True)\n",
        "\n",
        "if not os.path.exists(XCODEC2_PATH):\n",
        "    print('📥 Downloading xcodec2 checkpoint (~1.1GB)...')\n",
        "    subprocess.run([\n",
        "        'aria2c', '-x', '16', '-s', '16', '-k', '1M',\n",
        "        '-o', 'checkpoint.pt', '-d', XCODEC2_DIR, XCODEC2_URL\n",
        "    ], check=True)\n",
        "    print(f'✅ xcodec2 checkpoint saved to: {XCODEC2_PATH}')\n",
        "else:\n",
        "    print(f'✅ xcodec2 checkpoint already exists: {XCODEC2_PATH}')\n",
        "\n",
        "# ตรวจสอบขนาดไฟล์\n",
        "size_mb = os.path.getsize(XCODEC2_PATH) / (1024**2)\n",
        "print(f'📦 File size: {size_mb:.1f} MB')\n",
        "print(f'\\n🎯 เมื่อกด Save Version → Output จะมี xcodec2_ckpt/checkpoint.pt พร้อมใช้!')\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.10.12"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}