{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🇹🇭 Notebook 2: เทรนโมเดล InworldTTS ภาษาไทยด้วย LoRA บน Kaggle T4\n",
        "\n",
        "Notebook นี้จะนำข้อมูลที่เตรียมไว้จาก **Notebook 1** (เสียง + xcodec2 + Vectorized data) มาผ่านกระบวนการจนได้โมเดลพร้อมใช้งาน:\n",
        "\n",
        "| ขั้นตอน | สาระสำคัญ |\n",
        "|---------|----------|\n",
        "| 1. Environment Setup | โคลนโค้ด InworldTTS + ติดตั้ง Dependencies |\n",
        "| 2. Load Dataset | ชี้เป้าไปยังโฟลเดอร์ `dataset/` จาก Notebook 1 |\n",
        "| 3. ตรวจสอบ Input | ตรวจ xcodec2 + Vectorized data จาก Notebook 1 (อ่านจาก Input ฟรี) |\n",
        "| 4. SFT + LoRA Training | ฝึกฝน LLaMA ให้เชื่อมข้อความไทย ↔ เสียง |\n",
        "| 5. Cleanup | ทำความสะอาด Working Disk ก่อนเซฟโมเดล |\n",
        "| 6. Checkpoint Conversion | Merge LoRA → โมเดลพร้อมเสิร์ฟ |\n",
        "| 7. Inference Test | ทดสอบโคลนเสียงสดจากผลลัพธ์ที่เทรน |\n",
        "\n",
        "> ⚠️ **ข้อกำหนด Kaggle:** เปิด GPU (T4 x2), เปิด Internet Access, และเพิ่ม Output ของ Notebook 1 เป็น Input Dataset\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## 🎛️ Control Panel — ศูนย์รวมค่าปรับแต่งทั้งหมด\n",
        "แก้ไขค่าด้านล่างนี้เพียงจุดเดียว ทุก Cell ด้านล่างจะอ้างอิงจากตรงนี้โดยอัตโนมัติ\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ================================================================\n",
        "# 🎛️ CONTROL PANEL — ปรับค่าทั้งหมดได้ที่นี่จุดเดียว!\n",
        "# ================================================================\n",
        "# ℹ️ ทุกค่าด้านล่างถูกวิเคราะห์แล้วสำหรับ Kaggle T4 x2 (VRAM 15GB/GPU)\n",
        "# ℹ️ VRAM รวมจะใช้ ~11-13GB จาก 15GB ต่อ GPU (มี headroom ~2-4GB)\n",
        "# ℹ️ เวลาเทรนโดยประมาณ: ~2 ชั่วโมง (จาก limit 12 ชม.)\n",
        "\n",
        "# --- 🔑 Credentials ---\n",
        "HF_TOKEN = 'YOUR_HF_TOKEN_HERE'  # Token สำหรับดาวน์โหลด Llama จาก HuggingFace\n",
        "\n",
        "# --- 📂 Paths & Dataset ---\n",
        "REPO_URL    = 'https://github.com/chalitbkb/Inworldtts.git'\n",
        "REPO_DIR    = '/kaggle/working/Inworldtts'\n",
        "INPUT_NOTEBOOK_NAME = 'notebooks/chalitsuporntawee/download-mcv-thai'  # ชื่อ Output ของ Notebook 1\n",
        "\n",
        "# --- 🔊 xcodec2 Audio Codec (หูและปากของโมเดล) ---\n",
        "# ℹ️ ไฟล์นี้ถูกดาวน์โหลดไว้แล้วใน Notebook 1 → อ่านจาก Input ฟรีไม่กิน Working Disk!\n",
        "# ℹ️ ถ้าย้ายชื่อ Notebook 1 → แก้ INPUT_NOTEBOOK_NAME ด้านบน ค่านี้จะปรับตามอัตโนมัติ\n",
        "XCODEC2_DIR  = f'/kaggle/input/{INPUT_NOTEBOOK_NAME}/xcodec2_ckpt'\n",
        "XCODEC2_PATH = f'{XCODEC2_DIR}/checkpoint.pt'  # ใช้ทั้ง Encoder + Decoder\n",
        "\n",
        "# --- 🧬 Vectorized Data (เตรียมไว้แล้วใน Notebook 1) ---\n",
        "# ℹ️ ข้อมูลที่ผ่านการ Vectorize แล้ว อ่านจาก Input ฟรี ไม่กิน Working Disk\n",
        "VECTORIZED_DIR = f'/kaggle/input/{INPUT_NOTEBOOK_NAME}/vectorized_th'\n",
        "\n",
        "# --- 🧬 Vectorization Settings (ค่าด้านล่างไม่ได้ใช้แล้ว — ย้ายไป Notebook 1) ---\n",
        "VEC_BATCH_SIZE  = 16    # จำนวนไฟล์เสียงต่อรอบที่ส่งเข้า Encoder พร้อมกัน\n",
        "                        # ↑ T4 15GB: Encoder (w2v-bert-2.0) ใช้ ~0.8GB/batch\n",
        "                        #   batch=16 ใช้ ~13GB (รีดเต็มกำลังโดยไม่ OOM)\n",
        "VEC_NUM_WORKERS = 4     # จำนวน CPU threads โหลดข้อมูลเข้า GPU\n",
        "                        # ↑ Kaggle มี 4 CPU cores → ใส่ให้เต็มไม่ให้ GPU รอ\n",
        "VAL_SPLIT       = 0.005 # สัดส่วนข้อมูลเอาไว้ตรวจสอบ (0.5% ≈ 43 ตัวอย่าง)\n",
        "LANGUAGE        = 'th'  # รหัสภาษาไทย ISO 639-1\n",
        "\n",
        "# --- 🧠 SFT Training (ขั้นที่ 5: สอนโมเดล) ---\n",
        "MODEL_NAME      = 'meta-llama/Llama-3.2-1B-Instruct'  # Base LLM\n",
        "PRECISION       = '16-mixed'  # ความแม่นยำตัวเลข\n",
        "                              # ↑ 'bf16-mixed' เร็วกว่า แต่ T4 ไม่รองรับ\n",
        "                              #   '16-mixed' = fp16 + fp32 เหมาะ T4\n",
        "BATCH_SIZE      = 2     # จำนวนตัวอย่างต่อ GPU ต่อ step\n",
        "                        # ↑ LoRA r=64 + gradient_checkpointing → ใช้ ~12GB\n",
        "                        #   เหลือ ~3GB headroom ปลอดภัย ไม่ต้องลด\n",
        "GRAD_ACCUM      = 4     # สะสม gradient กี่ step ก่อนอัปเดตน้ำหนัก\n",
        "                        # ↑ Effective batch = 2 × 4 × 2GPU = 16 ตัวอย่าง\n",
        "                        #   ใหญ่พอให้ loss เสถียร ไม่กระโดดไปมา\n",
        "LEARNING_RATE   = 3e-5  # อัตราเร็วในการเรียนรู้\n",
        "                        # ↑ 3e-5 เหมาะกับ LoRA rank 16 — เรียนช้าแต่มั่นคง\n",
        "                        #   ป้องกัน Divergence (โมเดลหลงทาง) ที่เคยเกิดกับ 1e-4\n",
        "WARMUP_RATIO    = 0.1   # สัดส่วน step ที่ค่อยๆ เพิ่ม LR ก่อนเรียนจริง\n",
        "                        # ↑ 10% = ~270 steps อุ่นเครื่อง → ป้องกัน loss กระเด้ง\n",
        "WEIGHT_DECAY    = 0.05  # ลงโทษน้ำหนักที่ใหญ่เกิน (ป้องกัน overfit)\n",
        "                        # ↑ 0.05 สมดุล: ไม่รัดแน่นเกินจน overfit\n",
        "                        #   ไม่หลวมเกินจนเรียนมั่ว (เดิม 0.1 รัดเกินไป)\n",
        "MAX_SEQ_LEN     = 2048  # ความยาว Sequence สูงสุด (tokens)\n",
        "                        # ↑ 2048 tok ÷ 50 tok/s ≈ 40 วินาทีเสียงสูงสุดต่อ clip\n",
        "                        #   ลดเหลือ 1536 ถ้า OOM (ลด VRAM ~25%)\n",
        "GRAD_CLIP       = 1.0   # จำกัด gradient ไม่ให้ใหญ่เกิน (ป้องกัน loss ระเบิด)\n",
        "                        # ↑ 1.0 = มาตรฐาน, ลดเป็น 0.5 ถ้า loss กระเด้ง\n",
        "NUM_WORKERS     = 4     # จำนวน CPU threads โหลดข้อมูลเทรน\n",
        "                        # ↑ =4 (เต็ม CPU cores Kaggle) ป้องกัน GPU รองาน\n",
        "STRATEGY        = 'ddp' # กลยุทธ์ Multi-GPU\n",
        "                        # ↑ 'ddp' = แต่ละ GPU ถือโมเดลเต็ม (เหมาะ Llama-1B)\n",
        "                        #   'fsdp'/'deepspeed' = แบ่งโมเดล (สำหรับ >3B เท่านั้น)\n",
        "GRAD_CHECKPOINT = True  # คำนวณซ้ำแทนเก็บใน VRAM\n",
        "                        # ↑ True = ประหยัด VRAM ~40% (จำเป็นบน T4!)\n",
        "                        #   แลกกับความเร็วลดลง ~20%\n",
        "\n",
        "# --- 🔧 LoRA (Low-Rank Adaptation — สอนโมเดลแบบประหยัด) ---\n",
        "LORA_R          = 16    # ขนาด 'สมอง' ที่เพิ่มเข้าไป (rank)\n",
        "                        # ↑ r=16 ≈ 14M params — สมดุลระหว่างเรียนรู้กับ Overfit\n",
        "                        #   r=64 เคย Diverge เพราะ capacity เกินข้อมูล\n",
        "LORA_ALPHA      = 32    # ตัวคูณพลังของ LoRA (มาตรฐาน = 2 × r)\n",
        "                        # ↑ alpha/r = 2.0 = น้ำหนัก LoRA ปรับค่าได้แรงเท่าเดิม\n",
        "LORA_DROPOUT    = 0.05  # โอกาสปิดเส้นทางสุ่ม (ป้องกัน overfit)\n",
        "                        # ↑ 0.05 เพียงพอเมื่อ r=16 ขนาดเล็กลงแล้ว\n",
        "LORA_MODULES    = []    # Modules ที่จะใส่ LoRA\n",
        "                        # ↑ ว่าง = ระบบหาทุก Linear layers อัตโนมัติ (แนะนำ)\n",
        "\n",
        "# --- 💾 Checkpointing (บันทึกจุดคืนค่า) ---\n",
        "SAVE_STEPS      = 100   # บันทึก checkpoint ทุกๆ กี่ step\n",
        "                        # ↑ เซฟถี่ขึ้น เพื่อจับ checkpoint ดีที่สุดไม่ให้หลุด\n",
        "                        #   checkpoint ขนาด ~230MB × 10 ≈ 2.3GB\n",
        "EVAL_STEPS      = 100   # ทดสอบ Loss บน Validation Set ทุกๆ กี่ step\n",
        "                        # ↑ ตรงจังหวะ SAVE_STEPS เพื่อเห็น loss ตอน save\n",
        "LOG_STEPS       = 50    # แสดงผล Train Loss ทุกๆ กี่ step\n",
        "                        # ↑ 50 = ถี่พอติดตามแนวโน้ม ไม่ท่วม console\n",
        "KEEP_N_CKPTS    = 3    # เก็บ checkpoint ล่าสุดกี่ไฟล์ (ลบเก่าอัตโนมัติ)\n",
        "                        # ↑ เก็บมากขึ้น! ป้องกันไม่ให้ checkpoint ดีถูกลบ\n",
        "\n",
        "# --- 📈 Epochs (จำนวนรอบเรียนรู้) ---\n",
        "# ℹ️ ค่านี้ถูกนำไปใช้ใน train_weighted_datasets เป็น 'weight'\n",
        "# ℹ️ โค้ด InworldTTS คำนวณ total_training_steps อัตโนมัติจากสูตร:\n",
        "#    total_steps = (samples × EPOCHS) / BATCH_SIZE / GPUs / GRAD_ACCUM\n",
        "#    ≈ (9,294 × 2) / 2 / 2 / 4 ≈ 1,162 steps\n",
        "NUM_EPOCHS      = 2.0   # จำนวนรอบเรียนรู้ (ดูข้อมูลซ้ำกี่รอบ)\n",
        "                        # ↑ 2.0 = เทรนพอดี ไม่เลยจุดที่ดีที่สุด\n",
        "                        #   ครั้งก่อน 5.0 ทำให้โมเดล Diverge หลัง Step 300\n",
        "\n",
        "# --- 🏷️ Run Identity ---\n",
        "RUN_NAME        = 'thai_tts_lora_sft'\n",
        "SEED            = 777   # เลข Random Seed (ค่าเดิม เพื่อ reproducibility)\n",
        "\n",
        "# --- 🎤 Inference Test ---\n",
        "TEXT_TO_SPEAK   = 'วันนี้อากาศดีมากเลยครับ ออกไปเดินเล่นกันไหม'\n",
        "\n",
        "print('✅ Control Panel loaded!')\n",
        "print(f'📐 Effective batch size: {BATCH_SIZE} × {GRAD_ACCUM} × 2 GPUs = {BATCH_SIZE*GRAD_ACCUM*2}')\n",
        "print(f'📐 Estimated steps: ~{int(9294 * NUM_EPOCHS / BATCH_SIZE / 2 / GRAD_ACCUM)} steps ({NUM_EPOCHS} epochs)')\n",
        "print(f'📐 Estimated time: ~{int(9294 * NUM_EPOCHS / BATCH_SIZE / 2 / GRAD_ACCUM * 2.5 / 60)} minutes')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 1: 🏗️ เตรียมสภาพแวดล้อม (Environment Setup)\n",
        "โคลนโค้ด InworldTTS จาก GitHub และติดตั้ง Dependencies ทั้งหมดที่จำเป็น\n",
        "รวมถึง `pythainlp` สำหรับระบบ Text Normalization ภาษาไทยขั้นสูง\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import os, subprocess, sys\n",
        "\n",
        "# โคลนโค้ดจาก GitHub (ถ้ายังไม่ได้โคลน)\n",
        "if not os.path.exists(REPO_DIR):\n",
        "    print('📥 Cloning InworldTTS repository...')\n",
        "    subprocess.run(['git', 'clone', REPO_URL, REPO_DIR], check=True)\n",
        "    print('✅ Clone complete!')\n",
        "else:\n",
        "    print('✅ Repository already exists, skipping clone.')\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "print(f'Working directory: {os.getcwd()}')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ติดตั้ง Dependencies ทั้งหมดให้ครบ (ระบุ --system สำหรับ Kaggle)\n",
        "# หมายเหตุ: Kaggle มี PyTorch + CUDA ติดตั้งมาให้แล้ว เราจะติดแค่ส่วนอื่น\n",
        "!pip install -e . --quiet 2>&1 | tail -5\n",
        "\n",
        "# ติดตั้ง pythainlp สำหรับ Text Normalization ภาษาไทย\n",
        "!pip install pythainlp --quiet\n",
        "\n",
        "# ติดตั้ง flash-attn สำหรับการ Attention ที่เร็วกว่า (ถ้า build ไม่ผ่านก็ไม่เป็นไร จะ fallback อัตโนมัติ)\n",
        "!pip install flash-attn --no-build-isolation --quiet 2>&1 | tail -3 || echo 'flash-attn build failed, will use default attention.'\n",
        "\n",
        "print('\\n✅ All dependencies installed!')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 2: 📦 นำเข้าชุดข้อมูล (Load Dataset from Notebook 1)\n",
        "อ่านกล่องวัตถุดิบ (`dataset/` ที่มี th_wavs/ + train.jsonl) ที่เตรียมไว้จาก Notebook 1\n",
        "และอัปเดต path ในไฟล์ `train.jsonl` ให้ตรงกับตำแหน่ง Input บน Kaggle\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json, glob\n",
        "\n",
        "# ใช้ INPUT_NOTEBOOK_NAME จาก Control Panel\n",
        "INPUT_BASE = f'/kaggle/input/{INPUT_NOTEBOOK_NAME}/dataset'\n",
        "\n",
        "# ตรวจสอบว่าโฟลเดอร์ Input มีอยู่จริง\n",
        "if not os.path.exists(INPUT_BASE):\n",
        "    # ลองหาอัตโนมัติ\n",
        "    candidates = glob.glob('/kaggle/input/*/dataset')\n",
        "    if candidates:\n",
        "        INPUT_BASE = candidates[0]\n",
        "        print(f'🔍 Auto-detected dataset at: {INPUT_BASE}')\n",
        "    else:\n",
        "        raise FileNotFoundError(\n",
        "            '❌ ไม่พบโฟลเดอร์ dataset! กรุณาเพิ่ม Output ของ Notebook 1 เป็น Input ก่อน.\\n'\n",
        "            '   วิธี: Add Input → Your Work → เลือก Notebook 1'\n",
        "        )\n",
        "\n",
        "INPUT_WAV_DIR = os.path.join(INPUT_BASE, 'th_wavs')\n",
        "INPUT_JSONL = os.path.join(INPUT_BASE, 'train.jsonl')\n",
        "\n",
        "# นับจำนวนไฟล์\n",
        "num_wavs = len(glob.glob(os.path.join(INPUT_WAV_DIR, '*.wav')))\n",
        "num_jsonl_lines = sum(1 for _ in open(INPUT_JSONL, 'r', encoding='utf-8'))\n",
        "\n",
        "print(f'📂 WAV Directory : {INPUT_WAV_DIR}  ({num_wavs} files)')\n",
        "print(f'📄 JSONL File    : {INPUT_JSONL}  ({num_jsonl_lines} entries)')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# อัปเดต wav_path ใน JSONL ให้ชี้ไปที่ Input จริงบน Kaggle\n",
        "# (เพราะตอน Notebook 1 สร้าง JSONL มันชี้ไปที่ /kaggle/working/... แต่ตอนนี้มันอยู่ที่ /kaggle/input/...)\n",
        "\n",
        "WORKING_JSONL = '/kaggle/working/train_thai.jsonl'\n",
        "\n",
        "updated_count = 0\n",
        "with open(INPUT_JSONL, 'r', encoding='utf-8') as f_in, \\\n",
        "     open(WORKING_JSONL, 'w', encoding='utf-8') as f_out:\n",
        "    for line in f_in:\n",
        "        entry = json.loads(line.strip())\n",
        "        # อัปเดต path ให้ชี้ไปที่ Input ที่ถูกต้อง\n",
        "        old_path = entry['wav_path']\n",
        "        wav_filename = os.path.basename(old_path)\n",
        "        entry['wav_path'] = os.path.join(INPUT_WAV_DIR, wav_filename)\n",
        "\n",
        "        # เติม Metadata ป้องกันข้อมูลโดน Filter ทิ้งโดย Data Vectorizer\n",
        "        entry['language'] = LANGUAGE\n",
        "        if 'duration' not in entry: entry['duration'] = 5.0\n",
        "        if 'sample_rate' not in entry: entry['sample_rate'] = 48000\n",
        "\n",
        "        f_out.write(json.dumps(entry, ensure_ascii=False) + '\\n')\n",
        "        updated_count += 1\n",
        "\n",
        "print(f'✅ Updated {updated_count} entries → {WORKING_JSONL}')\n",
        "\n",
        "# แสดงตัวอย่าง 3 บรรทัดแรก\n",
        "with open(WORKING_JSONL, 'r', encoding='utf-8') as f:\n",
        "    for i, line in enumerate(f):\n",
        "        if i >= 3: break\n",
        "        print(json.loads(line))\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 3: ✅ ตรวจสอบข้อมูลจาก Notebook 1\n",
        "ตรวจสอบว่า xcodec2 checkpoint และ Vectorized data ที่เตรียมไว้ใน Notebook 1 พร้อมใช้งาน\n",
        "\n",
        "> 💡 ข้อมูลทั้งหมดถูกเตรียมไว้แล้วใน Output ของ Notebook 1\n",
        "> Notebook 2 อ่านจาก Input ฟรีๆ ไม่กิน Working Disk เลย!\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ✅ ตรวจสอบว่าไฟล์จาก Notebook 1 พร้อมใช้ (อ่านจาก Input ตรงๆ ไม่ต้องคัดลอก!)\n",
        "\n",
        "# --- ตรวจสอบ xcodec2 ---\n",
        "if os.path.exists(XCODEC2_PATH):\n",
        "    size_mb = os.path.getsize(XCODEC2_PATH) / (1024**2)\n",
        "    print(f'✅ xcodec2: {XCODEC2_PATH} ({size_mb:.1f} MB)')\n",
        "else:\n",
        "    raise FileNotFoundError(f'❌ ไม่พบ xcodec2: {XCODEC2_PATH}')\n",
        "\n",
        "# --- ตรวจสอบ Vectorized data ---\n",
        "if os.path.exists(VECTORIZED_DIR):\n",
        "    print(f'✅ Vectorized data: {VECTORIZED_DIR}')\n",
        "    !ls -lh {VECTORIZED_DIR}/\n",
        "else:\n",
        "    raise FileNotFoundError(f'❌ ไม่พบ Vectorized data: {VECTORIZED_DIR}')\n",
        "\n",
        "# ใช้ xcodec2 จาก Input โดยตรง — ไม่ต้องคัดลอกมาใน Working!\n",
        "# (Notebook 1 วาง model_config.json ไว้ข้างๆ checkpoint.pt เรียบร้อยแล้ว)\n",
        "CODEC_MODEL_PATH = XCODEC2_PATH\n",
        "\n",
        "print(f'\\n🎯 ทุกอย่างพร้อม! Codec: {CODEC_MODEL_PATH} | Data: {VECTORIZED_DIR}')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 5: 🧠 ฝึกฝนสมองกล LoRA (SFT Fine-Tuning)\n",
        "หัวใจสำคัญที่สุดของ Notebook นี้!\n",
        "\n",
        "เราจะสร้างไฟล์ตั้งค่า `sft_thai.json` ที่ปรับแต่งมาอย่างพิถีพิถันสำหรับ:\n",
        "- **Kaggle T4 (15GB VRAM):** ใช้ precision `16-mixed` (เพราะ T4 ไม่รองรับ bf16)\n",
        "- **LoRA:** เทรนเฉพาะชิปเสริม `r=16` กิน VRAM น้อย แต่เรียนรู้ได้ดี\n",
        "- **Gradient Checkpointing:** ประหยัด VRAM เพิ่มเติม โดยแลกกับความเร็วที่ลดลงเล็กน้อย\n",
        "- **Gradient Accumulation:** จำลอง batch_size ใหญ่ขึ้น ช่วยให้ Loss ลดได้เสถียร\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "\n",
        "# ============================================================\n",
        "# สร้างไฟล์ตั้งค่า SFT (อ้างอิงค่าจาก Control Panel ด้านบน)\n",
        "# ============================================================\n",
        "sft_config = {\n",
        "    'training': {\n",
        "        'seed': SEED,\n",
        "        'logging_steps': LOG_STEPS,\n",
        "        'eval_steps': EVAL_STEPS,\n",
        "        'gradient_accumulation_steps': GRAD_ACCUM,\n",
        "        'gradient_clip_value': GRAD_CLIP,\n",
        "        'learning_rate': LEARNING_RATE,\n",
        "        'betas': [0.9, 0.95],\n",
        "        'warmup_ratio': WARMUP_RATIO,\n",
        "        'batch_size': BATCH_SIZE,\n",
        "        'weight_decay': WEIGHT_DECAY,\n",
        "        'precision': PRECISION,\n",
        "        'strategy': STRATEGY,\n",
        "        'gradient_checkpointing': GRAD_CHECKPOINT,\n",
        "        'num_workers': NUM_WORKERS\n",
        "    },\n",
        "    'modeling': {\n",
        "        'parameters': {\n",
        "            'codebook_size': 65536,\n",
        "            'max_seq_len': MAX_SEQ_LEN,\n",
        "            'model_name': MODEL_NAME,\n",
        "            'enable_text_normalization': True\n",
        "        }\n",
        "    },\n",
        "    'lora': {\n",
        "        'task_type': 'CAUSAL_LM',\n",
        "        'r': LORA_R,\n",
        "        'lora_alpha': LORA_ALPHA,\n",
        "        'target_modules': LORA_MODULES,\n",
        "        'lora_dropout': LORA_DROPOUT,\n",
        "        'bias': 'none'\n",
        "    },\n",
        "    'checkpointing': {\n",
        "        'save_steps': SAVE_STEPS,\n",
        "        'collect_health_stats': False,\n",
        "        'save_intermediate_generations': False,\n",
        "        'only_load_model_weights': True,\n",
        "        'keep_only_last_n_checkpoints': KEEP_N_CKPTS\n",
        "    },\n",
        "    'train_weighted_datasets': {\n",
        "        VECTORIZED_DIR: NUM_EPOCHS  # ← จำนวน epoch! (5.0 = ดูข้อมูลซ้ำ 5 รอบ)\n",
        "    },\n",
        "    'val_weighted_datasets': {\n",
        "        VECTORIZED_DIR: 1.0  # Validation ไม่ต้องซ้ำหลายรอบ\n",
        "    },\n",
        "    'dataset': {\n",
        "        'allowed_languages': [LANGUAGE],\n",
        "        'min_dnsmos_score': 0,\n",
        "        'min_sample_rate': 0,\n",
        "        'enable_rlhf_training': False,\n",
        "        'min_audio_duration': 0.5  # ตัด clip สั้นกว่า 0.5 วินาที (อาจเป็น noise)\n",
        "    }\n",
        "}\n",
        "\n",
        "SFT_CONFIG_PATH = '/kaggle/working/sft_thai.json'\n",
        "with open(SFT_CONFIG_PATH, 'w') as f:\n",
        "    json.dump(sft_config, f, indent=4)\n",
        "\n",
        "print('✅ SFT Config saved to:', SFT_CONFIG_PATH)\n",
        "print(json.dumps(sft_config, indent=2))\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🔑 คำอธิบายค่าที่ตั้งไว้:\n",
        "\n",
        "| พารามิเตอร์ | ค่า | เหตุผล |\n",
        "|-------------|-----|--------|\n",
        "| `precision` | `16-mixed` | T4 ไม่รองรับ bf16 ต้องใช้ fp16 mixed |\n",
        "| `batch_size` | `2` | VRAM 15GB ของ T4 รองรับได้แค่นี้ |\n",
        "| `gradient_accumulation_steps` | `4` | จำลอง effective batch = 8 ช่วยให้ Loss เสถียร |\n",
        "| `gradient_checkpointing` | `true` | ประหยัด VRAM ~40% |\n",
        "| `learning_rate` | `3e-05` | ลด LR ป้องกันโมเดลหลงทาง (Diverge) ที่เคยเกิดกับ 1e-4 |\n",
        "| `lora.r` | `16` | สมดุลระหว่างเรียนรู้กับป้องกัน Overfit |\n",
        "| `lora.lora_alpha` | `32` | = 2 × r ตามสูตรมาตรฐาน |\n",
        "| `lora.target_modules` | `[]` | ว่างไว้ = ระบบจะหา Linear Layers อัตโนมัติ |\n",
        "| `keep_only_last_n_checkpoints` | `3` | ประหยัดพื้นที่ Kaggle ไม่เก็บ checkpoint เก่า |\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🔐 Login to HuggingFace (ใช้ HF_TOKEN จาก Control Panel)\n",
        "if HF_TOKEN != 'YOUR_HF_TOKEN_HERE':\n",
        "    !huggingface-cli login --token {HF_TOKEN}\n",
        "    print('✅ Logged in to HuggingFace!')\n",
        "else:\n",
        "    print('⚠️ กรุณาใส่ HF_TOKEN ใน Control Panel ด้านบนก่อน!')\n",
        "    print('   ไปที่: https://huggingface.co/settings/tokens')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🚀 เริ่มเทรน SFT + LoRA!\n",
        "os.chdir(REPO_DIR)\n",
        "os.environ['TOKENIZERS_PARALLELISM'] = 'false'\n",
        "\n",
        "EXPERIMENT_DIR = '/kaggle/working/experiments'\n",
        "\n",
        "import torch\n",
        "nproc = torch.cuda.device_count() or 1\n",
        "print(f'⚡ Training with {nproc} GPUs via Lightning Fabric')\n",
        "\n",
        "# ใช้ fabric run (ไม่ใช่ torchrun!) เพราะโปรเจคนี้ใช้ Lightning Fabric จัดการ Multi-GPU\n",
        "# สำคัญ: ต้องมี -- คั่นก่อน flags ของ main.py\n",
        "!fabric run --accelerator=gpu --devices={nproc} tts/training/main.py -- \\\n",
        "    --config_path={SFT_CONFIG_PATH} \\\n",
        "    --run_name={RUN_NAME} \\\n",
        "    --experiment_dir={EXPERIMENT_DIR} \\\n",
        "    --seed={SEED}\n",
        "\n",
        "print('\\n🎉 SFT Training complete!')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 6: 🧹 ทำความสะอาด & แปลงโมเดล (Cleanup & Checkpoint Conversion)\n",
        "ลบ checkpoint ระหว่างเทรน (เก็บไว้แค่ final) เพื่อเปิดพื้นที่ disk\n",
        "จากนั้นแปลง LoRA Checkpoint ให้อยู่ในรูปแบบพร้อมเสิร์ฟ (Serving Format)\n",
        "เพื่อนำไปทำ Zero-Shot Voice Cloning ได้ทันที\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import shutil, glob\n",
        "\n",
        "# 1. ลบ Checkpoint เก่าระหว่างเทรน (ขนาดใหญ่มาก) เก็บไว้แค่ final_model.pt\n",
        "EXPERIMENT_DIR = '/kaggle/working/experiments'\n",
        "checkpoints = glob.glob(os.path.join(EXPERIMENT_DIR, RUN_NAME, 'checkpoint_*.pt'))\n",
        "for ckpt in checkpoints:\n",
        "    if os.path.exists(ckpt):\n",
        "        size_gb = os.path.getsize(ckpt) / (1024**3)\n",
        "        print(f'🗑️ Removing {ckpt} ({size_gb:.2f} GB)...')\n",
        "        os.remove(ckpt)\n",
        "\n",
        "# 2. ลบไฟล์ JSONL ชั่วคราว\n",
        "if os.path.exists(WORKING_JSONL):\n",
        "    os.remove(WORKING_JSONL)\n",
        "\n",
        "print('\\n✅ Cleanup complete! Area cleared for Saving the Model.')\n",
        "\n",
        "# ตรวจสอบพื้นที่ว่างบนดิสก์\n",
        "!df -h /kaggle/working\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ค้นหา Checkpoint ที่เทรนเสร็จล่าสุด\n",
        "CHECKPOINT_DIR = os.path.join(EXPERIMENT_DIR, RUN_NAME)\n",
        "\n",
        "# หา checkpoint ไฟล์ล่าสุด\n",
        "checkpoint_files = sorted(glob.glob(os.path.join(CHECKPOINT_DIR, '*.pt')))\n",
        "if not checkpoint_files:\n",
        "    print('❌ ไม่พบ checkpoint! กรุณาตรวจสอบว่าการเทรนสำเร็จหรือไม่')\n",
        "else:\n",
        "    LATEST_CHECKPOINT = checkpoint_files[-1]  # ไฟล์ล่าสุด\n",
        "    print(f'📦 Latest checkpoint: {LATEST_CHECKPOINT}')\n",
        "    print(f'📦 All checkpoints:')\n",
        "    for cp in checkpoint_files:\n",
        "        size_mb = os.path.getsize(cp) / (1024**2)\n",
        "        print(f'   {os.path.basename(cp)} ({size_mb:.1f} MB)')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# แปลง Checkpoint เป็นรูปแบบ Serving (Merge LoRA เข้ากับ Base Model)\n",
        "SERVING_DIR = '/kaggle/working/ready_to_serving'\n",
        "os.makedirs(SERVING_DIR, exist_ok=True)\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "\n",
        "!python tools/serving/convert_checkpoint.py \\\n",
        "    --checkpoint_path={LATEST_CHECKPOINT} \\\n",
        "    --output_path={SERVING_DIR} \\\n",
        "    --merge_lora=true \\\n",
        "    --update_eos_token=true\n",
        "\n",
        "print('\\n✅ Model converted to serving format!')\n",
        "print(f'📂 Serving directory: {SERVING_DIR}')\n",
        "!ls -lh {SERVING_DIR}/\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 7: 🎤 ทดสอบโคลนเสียงสด! (Inference & Voice Cloning)\n",
        "เวลาแห่งความตื่นเต้น! เราจะทดสอบโมเดลที่เพิ่งเทรนเสร็จ\n",
        "โดยป้อนไฟล์เสียงตัวอย่างสั้นๆ (Prompt) + ข้อความที่ต้องการให้พูด\n",
        "แล้วฟังผลลัพธ์กันสดๆ!\n",
        "\n",
        "> 💡 สำหรับ Zero-Shot Voice Cloning:\n",
        "> แค่เปลี่ยนไฟล์เสียง Prompt เป็นเสียงของคนที่คุณต้องการโคลน (3-10 วินาที)\n",
        "> โมเดลจะเลียนแบบสำเนียงและโทนเสียงให้อัตโนมัติ!\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# เตรียมไฟล์เสียงตัวอย่างสำหรับทดสอบ (Zero-Shot Voice Cloning)\n",
        "# -------------------------------------------------------------\n",
        "# 1. ใส่ Path ของไฟล์เสียงของคุณเอง (3-10 วินาที ชัดเจน ไม่มีเสียงรบกวน)\n",
        "PROMPT_WAV = '/kaggle/input/datasets/chalitsuporntawee/my-voice/my_voice.wav'\n",
        "\n",
        "# 2. พิมพ์คำที่พูดในไฟล์เสียงนั้นให้เป๊ะทุกคำ\n",
        "PROMPT_TRANSCRIPTION = 'สวัสดีครับ ข้อความของคุณจะถูกประมวลผลชั่วคราวเพื่อสร้างเสียงเท่านั้น โคลนเสียงได้อย่างแม่นยำราวกับต้นฉบับและเปลี่ยนข้อความให้เป็นเสียงธรรมชาติด้วยความหน่วงต่ำ'\n",
        "\n",
        "print(f'🎵 Using Custom Prompt Audio: {PROMPT_WAV}')\n",
        "print(f'📝 Prompt Transcription: {PROMPT_TRANSCRIPTION}')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ข้อความใหม่ที่ต้องการให้โมเดลพูด (ใช้ TEXT_TO_SPEAK จาก Control Panel หรือพิมพ์ใหม่ที่นี่ก็ได้)\n",
        "# TEXT_TO_SPEAK = 'ประโยคใหม่ที่คุณอยากให้พูด'\n",
        "\n",
        "OUTPUT_WAV = '/kaggle/working/cloned_voice_output.wav'\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "\n",
        "!python tools/serving/inference.py \\\n",
        "    --model_checkpoint_path={SERVING_DIR} \\\n",
        "    --audio_encoder_path={CODEC_MODEL_PATH} \\\n",
        "    --audio_decoder_path={CODEC_MODEL_PATH} \\\n",
        "    --prompt_wav_path={PROMPT_WAV} \\\n",
        "    --prompt_transcription=\"{PROMPT_TRANSCRIPTION}\" \\\n",
        "    --text=\"{TEXT_TO_SPEAK}\" \\\n",
        "    --output_path={OUTPUT_WAV} \\\n",
        "    --enable_text_normalization=true \\\n",
        "    --language={LANGUAGE} \\\n",
        "    --seed=42\n",
        "\n",
        "print(f'\\n🎉 Output saved to: {OUTPUT_WAV}')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🔊 เล่นเสียงผลลัพธ์ใน Notebook!\n",
        "import IPython.display as ipd\n",
        "\n",
        "if os.path.exists(OUTPUT_WAV):\n",
        "    file_size = os.path.getsize(OUTPUT_WAV)\n",
        "    if file_size > 0:\n",
        "        print(f'🎧 ไฟล์เสียงขนาด: {file_size/1024:.1f} KB')\n",
        "        print('กดปุ่ม Play ด้านล่างเพื่อฟังผลลัพธ์!')\n",
        "        display(ipd.Audio(OUTPUT_WAV))\n",
        "    else:\n",
        "        print('⚠️ ไฟล์เสียงว่างเปล่า! โมเดลอาจยังเทรนไม่พอ')\n",
        "else:\n",
        "    print('❌ ไม่พบไฟล์เสียง output')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ✅ สรุปผลลัพธ์สุดท้าย\n",
        "\n",
        "เมื่อรันทุกขั้นตอนจนจบ คุณจะได้:\n",
        "\n",
        "| ไฟล์/โฟลเดอร์ | ตำแหน่ง | คำอธิบาย |\n",
        "|---------------|---------|----------|\n",
        "| `ready_to_serving/` | `/kaggle/working/ready_to_serving/` | โมเดลพร้อมเสิร์ฟ (LoRA + Base ผสานเป็นเนื้อเดียว) |\n",
        "| `cloned_voice_output.wav` | `/kaggle/working/` | เสียงโคลนทดสอบ |\n",
        "\n",
        "### 📌 วิธีนำไปใช้งานต่อ:\n",
        "1. กด **Save Version** เพื่อบันทึก Output\n",
        "2. ในภายหลัง สร้าง Notebook ใหม่ แล้วเพิ่ม Output ของ Notebook นี้เป็น Input\n",
        "3. โหลดโมเดลจากโฟลเดอร์ `ready_to_serving/` + Codec Checkpoint\n",
        "4. ป้อนเสียงตัวอย่าง 3-10 วินาที + ข้อความ → ได้เสียงโคลนภาษาไทย! 🇹🇭🎉\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.10.12"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
