{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🇹🇭 Notebook 2: เทรนโมเดล InworldTTS ภาษาไทยด้วย LoRA บน Kaggle T4\n",
        "\n",
        "Notebook นี้จะนำชุดข้อมูลเสียง (.wav + train.jsonl) ที่เตรียมไว้จาก **Notebook 1** มาผ่านกระบวนการ 7 ขั้นตอนจนได้โมเดลพร้อมใช้งาน:\n",
        "\n",
        "| ขั้นตอน | สาระสำคัญ |\n",
        "|---------|-----------|\n",
        "| 1. Environment Setup | โคลนโค้ด InworldTTS + ติดตั้ง Dependencies |\n",
        "| 2. Load Dataset | ชี้เป้าไปยังโฟลเดอร์ `dataset/` จาก Notebook 1 |\n",
        "| 3. Data Vectorization | แปลงไฟล์เสียง .wav → Acoustic Tokens ด้วย xcodec2 |\n",
        "| 4. Merge Shards | รวมไฟล์ชิ้นส่วน Vectorized ให้เป็นก้อนเดียว |\n",
        "| 5. SFT + LoRA Training | ฝึกฝน LLaMA ให้เชื่อมข้อความไทย ↔ เสียง |\n",
        "| 6. Checkpoint Conversion | แปลง LoRA → โมเดลพร้อมเสิร์ฟ |\n",
        "| 7. Inference Test | ทดสอบโคลนเสียงสดจากผลลัพธ์ที่เทรน |\n",
        "\n",
        "> ⚠️ **ข้อกำหนด Kaggle:** เปิด GPU (T4 x2), เปิด Internet Access, และเพิ่ม Output ของ Notebook 1 เป็น Input Dataset\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## 🎛️ Control Panel — ศูนย์รวมค่าปรับแต่งทั้งหมด\n",
        "แก้ไขค่าด้านล่างนี้เพียงจุดเดียว ทุก Cell ด้านล่างจะอ้างอิงจากตรงนี้โดยอัตโนมัติ\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ================================================================\n",
        "# 🎛️ CONTROL PANEL — ปรับค่าทั้งหมดได้ที่นี่จุดเดียว!\n",
        "# ================================================================\n",
        "\n",
        "# --- 🔑 Credentials ---\n",
        "HF_TOKEN = 'YOUR_HF_TOKEN_HERE'          # HuggingFace Token (จำเป็นสำหรับ Llama)\n",
        "\n",
        "# --- 📂 Paths & Dataset ---\n",
        "REPO_URL    = 'https://github.com/chalitbkb/Inworldtts.git'\n",
        "REPO_DIR    = '/kaggle/working/Inworldtts'\n",
        "INPUT_NOTEBOOK_NAME = 'notebooks/chalitgu2/download-mcv-thai' # ชื่อ Output ของ Notebook 1 บน Kaggle\n",
        "CODEC_URL   = 'https://huggingface.co/HKUSTAudio/xcodec2/resolve/main/ckpt/epoch=4-step=1400000.ckpt'\n",
        "\n",
        "# --- 🧬 Data Vectorization ---\n",
        "VEC_BATCH_SIZE  = 12      # ต่อ GPU (T4 ใช้ ~4-5GiB ต่อ batch=4, เพิ่มเป็น 12 ใช้ ~12-14GiB เต็มกำลัง)\n",
        "VEC_NUM_WORKERS = 2       # DataLoader workers ต่อ GPU (4 CPUs / 2 GPUs = 2)\n",
        "VAL_SPLIT       = 0.005   # สัดส่วนข้อมูล Validation (0.5%)\n",
        "LANGUAGE        = 'th'    # รหัสภาษา\n",
        "\n",
        "# --- 🧠 SFT Training ---\n",
        "MODEL_NAME      = 'meta-llama/Llama-3.2-1B-Instruct'\n",
        "PRECISION       = '16-mixed'   # T4 ใช้ '16-mixed', A100 ใช้ 'bf16-mixed'\n",
        "BATCH_SIZE      = 2            # ต่อ GPU (ลดเหลือ 1 ถ้า OOM)\n",
        "GRAD_ACCUM      = 4            # Effective batch = BATCH_SIZE × GRAD_ACCUM × GPUs\n",
        "LEARNING_RATE   = 5e-05\n",
        "WARMUP_RATIO    = 0.05\n",
        "WEIGHT_DECAY    = 0.1\n",
        "MAX_SEQ_LEN     = 2048         # ความยาว Sequence สูงสุด (ลดลงถ้า OOM)\n",
        "GRAD_CLIP       = 1.0\n",
        "NUM_WORKERS     = 2\n",
        "STRATEGY        = 'ddp'        # 'ddp' / 'fsdp' / 'deepspeed'\n",
        "GRAD_CHECKPOINT = True         # ประหยัด VRAM ~40% (ต้องเปิดบน T4)\n",
        "\n",
        "# --- 🔧 LoRA ---\n",
        "LORA_R          = 16           # Rank (8/16/32/64)\n",
        "LORA_ALPHA      = 32           # มักเท่ากับ 2 × r\n",
        "LORA_DROPOUT    = 0.05         # Dropout (0.0 - 0.1)\n",
        "LORA_MODULES    = []           # ว่าง = AUTO detect ทุก Linear layers\n",
        "\n",
        "# --- 💾 Checkpointing ---\n",
        "SAVE_STEPS      = 200\n",
        "EVAL_STEPS      = 200\n",
        "LOG_STEPS       = 50\n",
        "KEEP_N_CKPTS    = 3            # เก็บ checkpoint ล่าสุดกี่ไฟล์\n",
        "\n",
        "# --- 🏷️ Run Identity ---\n",
        "RUN_NAME        = 'thai_tts_lora_sft'\n",
        "SEED            = 777\n",
        "\n",
        "# --- 🎤 Inference Test ---\n",
        "TEXT_TO_SPEAK   = 'วันนี้อากาศดีมากเลยครับ ออกไปเดินเล่นกันไหม'\n",
        "\n",
        "print('✅ Control Panel loaded!')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 1: 🏗️ เตรียมสภาพแวดล้อม (Environment Setup)\n",
        "โคลนโค้ด InworldTTS จาก GitHub และติดตั้ง Dependencies ทั้งหมดที่จำเป็น\n",
        "รวมถึง `pythainlp` สำหรับระบบ Text Normalization ภาษาไทยขั้นสูง\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import os, subprocess, sys\n",
        "\n",
        "# โคลนโค้ดจาก GitHub (ถ้ายังไม่ได้โคลน)\n",
        "if not os.path.exists(REPO_DIR):\n",
        "    print('📥 Cloning InworldTTS repository...')\n",
        "    subprocess.run(['git', 'clone', REPO_URL, REPO_DIR], check=True)\n",
        "    print('✅ Clone complete!')\n",
        "else:\n",
        "    print('✅ Repository already exists, skipping clone.')\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "print(f'Working directory: {os.getcwd()}')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ติดตั้ง Dependencies ทั้งหมดให้ครบ (ระบุ --system สำหรับ Kaggle)\n",
        "# หมายเหตุ: Kaggle มี PyTorch + CUDA ติดตั้งมาให้แล้ว เราจะติดแค่ส่วนอื่น\n",
        "!pip install -e . --quiet 2>&1 | tail -5\n",
        "\n",
        "# ติดตั้ง pythainlp สำหรับ Text Normalization ภาษาไทย\n",
        "!pip install pythainlp --quiet\n",
        "\n",
        "# ติดตั้ง flash-attn สำหรับการ Attention ที่เร็วกว่า (ถ้า build ไม่ผ่านก็ไม่เป็นไร จะ fallback อัตโนมัติ)\n",
        "!pip install flash-attn --no-build-isolation --quiet 2>&1 | tail -3 || echo 'flash-attn build failed, will use default attention.'\n",
        "\n",
        "print('\\n✅ All dependencies installed!')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 2: 📦 นำเข้าชุดข้อมูล (Load Dataset from Notebook 1)\n",
        "อ่านกล่องวัตถุดิบ (`dataset/` ที่มี th_wavs/ + train.jsonl) ที่เตรียมไว้จาก Notebook 1\n",
        "และอัปเดต path ในไฟล์ `train.jsonl` ให้ตรงกับตำแหน่ง Input บน Kaggle\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json, glob\n",
        "\n",
        "# ใช้ INPUT_NOTEBOOK_NAME จาก Control Panel\n",
        "INPUT_BASE = f'/kaggle/input/{INPUT_NOTEBOOK_NAME}/dataset'\n",
        "\n",
        "# ตรวจสอบว่าโฟลเดอร์ Input มีอยู่จริง\n",
        "if not os.path.exists(INPUT_BASE):\n",
        "    # ลองหาอัตโนมัติ\n",
        "    candidates = glob.glob('/kaggle/input/*/dataset')\n",
        "    if candidates:\n",
        "        INPUT_BASE = candidates[0]\n",
        "        print(f'🔍 Auto-detected dataset at: {INPUT_BASE}')\n",
        "    else:\n",
        "        raise FileNotFoundError(\n",
        "            '❌ ไม่พบโฟลเดอร์ dataset! กรุณาเพิ่ม Output ของ Notebook 1 เป็น Input ก่อน.\\n'\n",
        "            '   วิธี: Add Input → Your Work → เลือก Notebook 1'\n",
        "        )\n",
        "\n",
        "INPUT_WAV_DIR = os.path.join(INPUT_BASE, 'th_wavs')\n",
        "INPUT_JSONL = os.path.join(INPUT_BASE, 'train.jsonl')\n",
        "\n",
        "# นับจำนวนไฟล์\n",
        "num_wavs = len(glob.glob(os.path.join(INPUT_WAV_DIR, '*.wav')))\n",
        "num_jsonl_lines = sum(1 for _ in open(INPUT_JSONL, 'r', encoding='utf-8'))\n",
        "\n",
        "print(f'📂 WAV Directory : {INPUT_WAV_DIR}  ({num_wavs} files)')\n",
        "print(f'📄 JSONL File    : {INPUT_JSONL}  ({num_jsonl_lines} entries)')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# อัปเดต wav_path ใน JSONL ให้ชี้ไปที่ Input จริงบน Kaggle\n",
        "# (เพราะตอน Notebook 1 สร้าง JSONL มันชี้ไปที่ /kaggle/working/... แต่ตอนนี้มันอยู่ที่ /kaggle/input/...)\n",
        "\n",
        "WORKING_JSONL = '/kaggle/working/train_thai.jsonl'\n",
        "\n",
        "updated_count = 0\n",
        "with open(INPUT_JSONL, 'r', encoding='utf-8') as f_in, \\\n",
        "     open(WORKING_JSONL, 'w', encoding='utf-8') as f_out:\n",
        "    for line in f_in:\n",
        "        entry = json.loads(line.strip())\n",
        "        # อัปเดต path ให้ชี้ไปที่ Input ที่ถูกต้อง\n",
        "        old_path = entry['wav_path']\n",
        "        wav_filename = os.path.basename(old_path)\n",
        "        entry['wav_path'] = os.path.join(INPUT_WAV_DIR, wav_filename)\n",
        "\n",
        "        # เติม Metadata ป้องกันข้อมูลโดน Filter ทิ้งโดย Data Vectorizer\n",
        "        entry['language'] = LANGUAGE\n",
        "        if 'duration' not in entry: entry['duration'] = 5.0\n",
        "        if 'sample_rate' not in entry: entry['sample_rate'] = 48000\n",
        "\n",
        "        f_out.write(json.dumps(entry, ensure_ascii=False) + '\\n')\n",
        "        updated_count += 1\n",
        "\n",
        "print(f'✅ Updated {updated_count} entries → {WORKING_JSONL}')\n",
        "\n",
        "# แสดงตัวอย่าง 3 บรรทัดแรก\n",
        "with open(WORKING_JSONL, 'r', encoding='utf-8') as f:\n",
        "    for i, line in enumerate(f):\n",
        "        if i >= 3: break\n",
        "        print(json.loads(line))\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 3: 🧬 แปลงเสียงเป็น Acoustic Tokens (Data Vectorization)\n",
        "LLaMA เป็น AI ภาษาข้อความ มัน \"ฟัง\" เสียงตรงๆ ไม่ออก\n",
        "ขั้นตอนนี้จะใช้ตัวเข้ารหัสเสียง **xcodec2** อ่านไฟล์ .wav แล้วแปลงเป็นชุดตัวเลข (Acoustic Tokens)\n",
        "ที่ LLaMA พร้อมกลืนเข้าไปเรียนรู้\n",
        "\n",
        "> 💡 xcodec2 เป็น Codec ที่โปรเจค InworldTTS รองรับโดยตรงตาม README.md\n",
        "> หากคุณยังไม่มี Encoder Model ให้ดาวน์โหลดจาก HuggingFace: `HKUSTAudio/xcodec2`\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ดาวน์โหลด xcodec2 checkpoint สำหรับ Encoder\n",
        "CODEC_DIR = '/kaggle/working/xcodec2_ckpt'\n",
        "CODEC_MODEL_PATH = os.path.join(CODEC_DIR, 'checkpoint.pt')\n",
        "\n",
        "if not os.path.exists(CODEC_MODEL_PATH):\n",
        "    print('📥 Downloading xcodec2 checkpoint with wget...')\n",
        "    os.makedirs(CODEC_DIR, exist_ok=True)\n",
        "    !wget -q -O {CODEC_MODEL_PATH} {CODEC_URL}\n",
        "    print(f'✅ Codec checkpoint saved to: {CODEC_MODEL_PATH}')\n",
        "else:\n",
        "    print(f'✅ Codec checkpoint already exists: {CODEC_MODEL_PATH}')\n",
        "\n",
        "# คัดลอก model_config.json สำหรับ Decoder\n",
        "import shutil\n",
        "CODEC_CONFIG_SRC = os.path.join(REPO_DIR, 'example', 'codec', 'model_config.json')\n",
        "CODEC_CONFIG_DST = os.path.join(CODEC_DIR, 'model_config.json')\n",
        "if not os.path.exists(CODEC_CONFIG_DST):\n",
        "    shutil.copy2(CODEC_CONFIG_SRC, CODEC_CONFIG_DST)\n",
        "    print(f'✅ Copied model_config.json → {CODEC_CONFIG_DST}')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# รัน Data Vectorization (Kaggle รองรับ T4 x2 ดังนั้นประมวลผลคู่กันเลย)\n",
        "VECTORIZED_DIR = '/kaggle/working/vectorized_th'\n",
        "os.makedirs(VECTORIZED_DIR, exist_ok=True)\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "\n",
        "import subprocess\n",
        "import torch\n",
        "\n",
        "gpu_count = torch.cuda.device_count()\n",
        "nproc = gpu_count if gpu_count > 0 else 1\n",
        "print(f'⚡ GPUs available: {gpu_count}, using {nproc} for vectorization!')\n",
        "\n",
        "!torchrun --nproc_per_node={nproc} tools/data/data_vectorizer.py \\\n",
        "    --codec_model_path={CODEC_MODEL_PATH} \\\n",
        "    --batch_size={VEC_BATCH_SIZE} \\\n",
        "    --num_workers={VEC_NUM_WORKERS} \\\n",
        "    --compile_model \\\n",
        "    --dataset_path={WORKING_JSONL} \\\n",
        "    --output_dir={VECTORIZED_DIR} \\\n",
        "    --allowed_languages={LANGUAGE} \\\n",
        "    --val_split={VAL_SPLIT}\n",
        "\n",
        "print('\\n✅ Data Vectorization complete!')\n",
        "print(f'Output: {VECTORIZED_DIR}')\n",
        "!ls -lh {VECTORIZED_DIR}/\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 4: 🔗 รวมชิ้นส่วนข้อมูล (Merge Shards)\n",
        "ขั้นตอนนี้ตาม README.md ของผู้สร้างโปรเจค:\n",
        "เราจะนำไฟล์ Shard หลายๆ ชิ้น (จากการ Vectorize) มารวมกันเป็นไฟล์เดียว\n",
        "เพื่อให้ DataLoader ของ SFT สามารถโหลดข้อมูลได้เร็วและเสถียรที่สุด\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "os.chdir(REPO_DIR)\n",
        "\n",
        "!python tools/data/data_merger.py \\\n",
        "    --dataset_path={VECTORIZED_DIR} \\\n",
        "    --remove_shards\n",
        "\n",
        "print('\\n✅ Shards merged successfully!')\n",
        "!ls -lh {VECTORIZED_DIR}/\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 5: 🧠 ฝึกฝนสมองกล LoRA (SFT Fine-Tuning)\n",
        "หัวใจสำคัญที่สุดของ Notebook นี้!\n",
        "\n",
        "เราจะสร้างไฟล์ตั้งค่า `sft_thai.json` ที่ปรับแต่งมาอย่างพิถีพิถันสำหรับ:\n",
        "- **Kaggle T4 (15GB VRAM):** ใช้ precision `16-mixed` (เพราะ T4 ไม่รองรับ bf16)\n",
        "- **LoRA:** เทรนเฉพาะชิปเสริม `r=16` กิน VRAM น้อย แต่เรียนรู้ได้ดี\n",
        "- **Gradient Checkpointing:** ประหยัด VRAM เพิ่มเติม โดยแลกกับความเร็วที่ลดลงเล็กน้อย\n",
        "- **Gradient Accumulation:** จำลอง batch_size ใหญ่ขึ้น ช่วยให้ Loss ลดได้เสถียร\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "\n",
        "# ============================================================\n",
        "# สร้างไฟล์ตั้งค่า SFT (อ้างอิงค่าจาก Control Panel ด้านบน)\n",
        "# ============================================================\n",
        "sft_config = {\n",
        "    'training': {\n",
        "        'seed': SEED,\n",
        "        'logging_steps': LOG_STEPS,\n",
        "        'eval_steps': EVAL_STEPS,\n",
        "        'gradient_accumulation_steps': GRAD_ACCUM,\n",
        "        'gradient_clip_value': GRAD_CLIP,\n",
        "        'learning_rate': LEARNING_RATE,\n",
        "        'betas': [0.9, 0.95],\n",
        "        'warmup_ratio': WARMUP_RATIO,\n",
        "        'batch_size': BATCH_SIZE,\n",
        "        'weight_decay': WEIGHT_DECAY,\n",
        "        'precision': PRECISION,\n",
        "        'strategy': STRATEGY,\n",
        "        'gradient_checkpointing': GRAD_CHECKPOINT,\n",
        "        'num_workers': NUM_WORKERS\n",
        "    },\n",
        "    'modeling': {\n",
        "        'parameters': {\n",
        "            'codebook_size': 65536,\n",
        "            'max_seq_len': MAX_SEQ_LEN,\n",
        "            'model_name': MODEL_NAME,\n",
        "            'enable_text_normalization': True\n",
        "        }\n",
        "    },\n",
        "    'lora': {\n",
        "        'task_type': 'CAUSAL_LM',\n",
        "        'r': LORA_R,\n",
        "        'lora_alpha': LORA_ALPHA,\n",
        "        'target_modules': LORA_MODULES,\n",
        "        'lora_dropout': LORA_DROPOUT,\n",
        "        'bias': 'none'\n",
        "    },\n",
        "    'checkpointing': {\n",
        "        'save_steps': SAVE_STEPS,\n",
        "        'collect_health_stats': False,\n",
        "        'save_intermediate_generations': False,\n",
        "        'only_load_model_weights': True,\n",
        "        'keep_only_last_n_checkpoints': KEEP_N_CKPTS\n",
        "    },\n",
        "    'train_weighted_datasets': {\n",
        "        VECTORIZED_DIR: 1.0\n",
        "    },\n",
        "    'val_weighted_datasets': {\n",
        "        VECTORIZED_DIR: 1.0\n",
        "    },\n",
        "    'dataset': {\n",
        "        'allowed_languages': [LANGUAGE],\n",
        "        'min_dnsmos_score': 0,\n",
        "        'min_sample_rate': 0,\n",
        "        'enable_rlhf_training': False\n",
        "    }\n",
        "}\n",
        "\n",
        "SFT_CONFIG_PATH = '/kaggle/working/sft_thai.json'\n",
        "with open(SFT_CONFIG_PATH, 'w') as f:\n",
        "    json.dump(sft_config, f, indent=4)\n",
        "\n",
        "print('✅ SFT Config saved to:', SFT_CONFIG_PATH)\n",
        "print(json.dumps(sft_config, indent=2))\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🔑 คำอธิบายค่าที่ตั้งไว้:\n",
        "\n",
        "| พารามิเตอร์ | ค่า | เหตุผล |\n",
        "|-------------|-----|--------|\n",
        "| `precision` | `16-mixed` | T4 ไม่รองรับ bf16 ต้องใช้ fp16 mixed |\n",
        "| `batch_size` | `2` | VRAM 15GB ของ T4 รองรับได้แค่นี้ |\n",
        "| `gradient_accumulation_steps` | `4` | จำลอง effective batch = 8 ช่วยให้ Loss เสถียร |\n",
        "| `gradient_checkpointing` | `true` | ประหยัด VRAM ~40% |\n",
        "| `learning_rate` | `5e-05` | LoRA ไม่ต้องใช้ LR สูง เพราะ Base ถูก Freeze |\n",
        "| `lora.r` | `16` | Sweet Spot สำหรับ TTS Voice Cloning |\n",
        "| `lora.lora_alpha` | `32` | = 2 × r ตามสูตรมาตรฐาน |\n",
        "| `lora.target_modules` | `[]` | ว่างไว้ = ระบบจะหา Linear Layers อัตโนมัติ |\n",
        "| `keep_only_last_n_checkpoints` | `3` | ประหยัดพื้นที่ Kaggle ไม่เก็บ checkpoint เก่า |\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🔐 Login to HuggingFace (ใช้ HF_TOKEN จาก Control Panel)\n",
        "if HF_TOKEN != 'YOUR_HF_TOKEN_HERE':\n",
        "    !huggingface-cli login --token {HF_TOKEN}\n",
        "    print('✅ Logged in to HuggingFace!')\n",
        "else:\n",
        "    print('⚠️ กรุณาใส่ HF_TOKEN ใน Control Panel ด้านบนก่อน!')\n",
        "    print('   ไปที่: https://huggingface.co/settings/tokens')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🚀 เริ่มเทรน SFT + LoRA!\n",
        "os.chdir(REPO_DIR)\n",
        "os.environ['TOKENIZERS_PARALLELISM'] = 'false'\n",
        "\n",
        "EXPERIMENT_DIR = '/kaggle/working/experiments'\n",
        "\n",
        "import torch\n",
        "nproc = torch.cuda.device_count() or 1\n",
        "print(f'⚡ Training with {nproc} GPUs via Lightning Fabric')\n",
        "\n",
        "# ใช้ fabric run (ไม่ใช่ torchrun!) เพราะโปรเจคนี้ใช้ Lightning Fabric จัดการ Multi-GPU\n",
        "# สำคัญ: ต้องมี -- คั่นก่อน flags ของ main.py\n",
        "!fabric run --accelerator=gpu --devices={nproc} tts/training/main.py -- \\\n",
        "    --config_path={SFT_CONFIG_PATH} \\\n",
        "    --run_name={RUN_NAME} \\\n",
        "    --experiment_dir={EXPERIMENT_DIR} \\\n",
        "    --seed={SEED}\n",
        "\n",
        "print('\\n🎉 SFT Training complete!')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 6: 🧹 ทำความสะอาด & แปลงโมเดล (Cleanup & Checkpoint Conversion)\n",
        "กำจัดไฟล์ขยะจากขั้นตอน Vectorization ที่ทำเสร็จแล้ว (อาจใหญ่ถึง 15-20GB)\n",
        "จากนั้นแปลง LoRA Checkpoint ให้อยู่ในรูปแบบพร้อมเสิร์ฟ (Serving Format)\n",
        "เพื่อนำไปทำ Zero-Shot Voice Cloning ได้ทันที\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import shutil, glob\n",
        "\n",
        "# ลบไฟล์ Vectorized ที่ใหญ่มาก (ไม่ต้องการแล้วหลังเทรนเสร็จ)\n",
        "for cleanup_dir in [VECTORIZED_DIR]:\n",
        "    if os.path.exists(cleanup_dir):\n",
        "        size_gb = sum(\n",
        "            os.path.getsize(os.path.join(dp, f))\n",
        "            for dp, dn, filenames in os.walk(cleanup_dir)\n",
        "            for f in filenames\n",
        "        ) / (1024**3)\n",
        "        print(f'🗑️ Removing {cleanup_dir} ({size_gb:.2f} GB)...')\n",
        "        shutil.rmtree(cleanup_dir)\n",
        "\n",
        "# ลบ JSONL ที่ทำขึ้นมาชั่วคราว\n",
        "if os.path.exists(WORKING_JSONL):\n",
        "    os.remove(WORKING_JSONL)\n",
        "\n",
        "print('✅ Cleanup complete!')\n",
        "\n",
        "# แสดงพื้นที่ดิสก์ที่เหลือ\n",
        "!df -h /kaggle/working | tail -1\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ค้นหา Checkpoint ที่เทรนเสร็จล่าสุด\n",
        "CHECKPOINT_DIR = os.path.join(EXPERIMENT_DIR, RUN_NAME)\n",
        "\n",
        "# หา checkpoint ไฟล์ล่าสุด\n",
        "checkpoint_files = sorted(glob.glob(os.path.join(CHECKPOINT_DIR, '*.pt')))\n",
        "if not checkpoint_files:\n",
        "    print('❌ ไม่พบ checkpoint! กรุณาตรวจสอบว่าการเทรนสำเร็จหรือไม่')\n",
        "else:\n",
        "    LATEST_CHECKPOINT = checkpoint_files[-1]  # ไฟล์ล่าสุด\n",
        "    print(f'📦 Latest checkpoint: {LATEST_CHECKPOINT}')\n",
        "    print(f'📦 All checkpoints:')\n",
        "    for cp in checkpoint_files:\n",
        "        size_mb = os.path.getsize(cp) / (1024**2)\n",
        "        print(f'   {os.path.basename(cp)} ({size_mb:.1f} MB)')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# แปลง Checkpoint เป็นรูปแบบ Serving (Merge LoRA เข้ากับ Base Model)\n",
        "SERVING_DIR = '/kaggle/working/ready_to_serving'\n",
        "os.makedirs(SERVING_DIR, exist_ok=True)\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "\n",
        "!python tools/serving/convert_checkpoint.py \\\n",
        "    --checkpoint_path={LATEST_CHECKPOINT} \\\n",
        "    --output_path={SERVING_DIR} \\\n",
        "    --merge_lora=true \\\n",
        "    --update_eos_token=true\n",
        "\n",
        "print('\\n✅ Model converted to serving format!')\n",
        "print(f'📂 Serving directory: {SERVING_DIR}')\n",
        "!ls -lh {SERVING_DIR}/\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ขั้นที่ 7: 🎤 ทดสอบโคลนเสียงสด! (Inference & Voice Cloning)\n",
        "เวลาแห่งความตื่นเต้น! เราจะทดสอบโมเดลที่เพิ่งเทรนเสร็จ\n",
        "โดยป้อนไฟล์เสียงตัวอย่างสั้นๆ (Prompt) + ข้อความที่ต้องการให้พูด\n",
        "แล้วฟังผลลัพธ์กันสดๆ!\n",
        "\n",
        "> 💡 สำหรับ Zero-Shot Voice Cloning:\n",
        "> แค่เปลี่ยนไฟล์เสียง Prompt เป็นเสียงของคนที่คุณต้องการโคลน (3-10 วินาที)\n",
        "> โมเดลจะเลียนแบบสำเนียงและโทนเสียงให้อัตโนมัติ!\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# เตรียมไฟล์เสียงตัวอย่างสำหรับทดสอบ\n",
        "# (ใช้ไฟล์เสียงภาษาไทยที่มีอยู่ในชุดข้อมูลเป็นตัวอย่าง)\n",
        "\n",
        "import glob, random\n",
        "\n",
        "# หาไฟล์เสียงตัวอย่างจาก Input\n",
        "wav_files = sorted(glob.glob(os.path.join(INPUT_WAV_DIR, '*.wav')))\n",
        "if wav_files:\n",
        "    PROMPT_WAV = random.choice(wav_files[:50])  # สุ่มจาก 50 ไฟล์แรก\n",
        "    print(f'🎵 Selected prompt audio: {PROMPT_WAV}')\n",
        "else:\n",
        "    print('⚠️ ไม่พบไฟล์เสียงตัวอย่าง กรุณาอัปโหลดไฟล์ .wav ของคุณเอง')\n",
        "    PROMPT_WAV = '/kaggle/working/my_voice.wav'\n",
        "\n",
        "# หา transcript ของไฟล์นั้นจาก JSONL\n",
        "PROMPT_TRANSCRIPTION = 'สวัสดีครับ'  # fallback\n",
        "jsonl_path = os.path.join(INPUT_BASE, 'train.jsonl')\n",
        "if os.path.exists(jsonl_path):\n",
        "    with open(jsonl_path, 'r', encoding='utf-8') as f:\n",
        "        for line in f:\n",
        "            entry = json.loads(line.strip())\n",
        "            if os.path.basename(entry.get('wav_path','')) == os.path.basename(PROMPT_WAV):\n",
        "                PROMPT_TRANSCRIPTION = entry['transcript']\n",
        "                break\n",
        "\n",
        "print(f'📝 Prompt transcription: {PROMPT_TRANSCRIPTION}')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ข้อความใหม่ที่ต้องการให้โมเดลพูด (ใช้ TEXT_TO_SPEAK จาก Control Panel)\n",
        "\n",
        "OUTPUT_WAV = '/kaggle/working/cloned_voice_output.wav'\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "\n",
        "!python tools/serving/inference.py \\\n",
        "    --model_checkpoint_path={SERVING_DIR} \\\n",
        "    --audio_encoder_path={CODEC_MODEL_PATH} \\\n",
        "    --audio_decoder_path={CODEC_MODEL_PATH} \\\n",
        "    --prompt_wav_path={PROMPT_WAV} \\\n",
        "    --prompt_transcription=\"{PROMPT_TRANSCRIPTION}\" \\\n",
        "    --text=\"{TEXT_TO_SPEAK}\" \\\n",
        "    --output_path={OUTPUT_WAV} \\\n",
        "    --enable_text_normalization=true \\\n",
        "    --language={LANGUAGE} \\\n",
        "    --seed=42\n",
        "\n",
        "print(f'\\n🎉 Output saved to: {OUTPUT_WAV}')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🔊 เล่นเสียงผลลัพธ์ใน Notebook!\n",
        "import IPython.display as ipd\n",
        "\n",
        "if os.path.exists(OUTPUT_WAV):\n",
        "    file_size = os.path.getsize(OUTPUT_WAV)\n",
        "    if file_size > 0:\n",
        "        print(f'🎧 ไฟล์เสียงขนาด: {file_size/1024:.1f} KB')\n",
        "        print('กดปุ่ม Play ด้านล่างเพื่อฟังผลลัพธ์!')\n",
        "        display(ipd.Audio(OUTPUT_WAV))\n",
        "    else:\n",
        "        print('⚠️ ไฟล์เสียงว่างเปล่า! โมเดลอาจยังเทรนไม่พอ')\n",
        "else:\n",
        "    print('❌ ไม่พบไฟล์เสียง output')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## ✅ สรุปผลลัพธ์สุดท้าย\n",
        "\n",
        "เมื่อรันทุกขั้นตอนจนจบ คุณจะได้:\n",
        "\n",
        "| ไฟล์/โฟลเดอร์ | ตำแหน่ง | คำอธิบาย |\n",
        "|---------------|---------|----------|\n",
        "| `ready_to_serving/` | `/kaggle/working/ready_to_serving/` | โมเดลพร้อมเสิร์ฟ (LoRA + Base ผสานเป็นเนื้อเดียว) |\n",
        "| `cloned_voice_output.wav` | `/kaggle/working/` | เสียงโคลนทดสอบ |\n",
        "\n",
        "### 📌 วิธีนำไปใช้งานต่อ:\n",
        "1. กด **Save Version** เพื่อบันทึก Output\n",
        "2. ในภายหลัง สร้าง Notebook ใหม่ แล้วเพิ่ม Output ของ Notebook นี้เป็น Input\n",
        "3. โหลดโมเดลจากโฟลเดอร์ `ready_to_serving/` + Codec Checkpoint\n",
        "4. ป้อนเสียงตัวอย่าง 3-10 วินาที + ข้อความ → ได้เสียงโคลนภาษาไทย! 🇹🇭🎉\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.10.12"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}